#!/bin/bash
if [[ $EUID -ne 0 ]]; then
  echo "You must be a root user" 2>&1
  exit 1
fi

[ -z "$1" ] && {
  echo "Missing channel!"
  echo "USAGE: $0 <CHANNEL> <PAN ID>"
  exit 1
}

[ -z "$2" ] && {
  echo "Missing PAN ID!"
  echo "USAGE: $0 <CHANNEL> <PAN ID>"
  exit 1
}

CHANNEL=$1
PANID=$2

# check for wpan0
ip link show wpan0 1> /dev/null 2>&1
if [[ $? == '0' ]] ; then
    echo ". taking wpan0 down"
    ip link set wpan0 down
else
    echo "! no wpan device found, exit!"
    exit 1
fi

# check for monitor0
ip link show monitor0 1> /dev/null 2>&1
[ $? == '0' ] && {
    echo ". delete monitor0"
    iwpan dev monitor0 del
}
# check for lowpan0
ip link show lowpan0 1> /dev/null 2>&1
if [[ $? == '0' ]]; then
    echo ". lowpan0 exists"
    ip link set lowpan0 down
else
    echo ". create lowpan0"
    ip link add link wpan0 name lowpan0 type lowpan
fi
iwpan phy phy0 set channel 0 $CHANNEL
iwpan dev wpan0 set pan_id $PANID
ip link set wpan0 up
ip link set lowpan0 up
# no UDP header compression support in RIOT (yet)
rmmod nhc_udp 1> /dev/null 2>&1
